version: "3"

services:
  db:
    container_name: laravel_db_dev
    build:
      context: ./db
    ports:
      - 3306:3306
    volumes:
      - laravel-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    platform: linux/x86_64
  app:
    container_name: laravel_app_dev
    build:
      context: ./app
    volumes:
      - ../src:/work/backend
    depends_on: ["db"]
  web:
    container_name: laravel_web_dev
    build:
      context: ./web
    ports:
      - 80:80
    volumes:
      - ../src:/work/backend
    depends_on: ["app"]

volumes:
  laravel-db:
